apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  namespace: cfg-ns
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: my-special-config
              key: special.type
restartPolicy: Never
