apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tomcat-operator
  template:
    metadata:
      labels:
        name: tomcat-operator
    spec:
      serviceAccountName: tomcat-operator
      containers:
        - name: tomcat-operator
          # Replace this with the built image name
          # image: REPLACE_IMAGE
          image: shidaqiu/tomcat-operator:v0.2
          command:
          - tomcat-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tomcat-operator"
