apiVersion: tomcat.apache.org/v1alpha1
kind: Tomcat
metadata:
  name: tomcat
spec:
  replicas: 2
  image: tomcat:latest
  imagePullPolicy: IfNotPresent
  webArchiveImage: ananwaresystems/webarchive:1.0
  deployDirectory: /usr/local/tomcat/webapps